log_aggregation_sys/data_logger/urls.py
from data_logger.views import (CpuDataView, DiskDataView, MemoryDataView,
                               SensorsDataView, main_menu_view)
from django.urls import path

app_name = "data_logger"

urlpatterns = [
    path("", main_menu_view, name="main_menu"),
    path("cpu_data/", CpuDataView.as_view(), name="cpu_data"),
    path("memory_data/", MemoryDataView.as_view(), name="memory_data"),
    path("sensors_data/", SensorsDataView.as_view(), name="sensors_data"),
    path("disk_data/", DiskDataView.as_view(), name="disk_data"),
]

log_aggregation_sys/log_aggregation_sys/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_logger.urls', namespace='data_logger')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

log_aggregation_sys/data_collector/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class LogCategory(models.TextChoices):
    INFORMATION = "INFO", _("Information")
    ERROR = "ERR", _("Error")
    WARNING = "WRN", _("Warning")


class CpuData(models.Model):
    user_time = models.FloatField(_("User Time"))
    nice_time = models.FloatField(_("Nice Time"))
    system_time = models.FloatField(_("System Time"))
    idle_time = models.FloatField(_("Idle Time"))
    cpu_percent = models.FloatField(_("%CPU"))
    cpu_time_percent_user = models.FloatField(_("%CPU User Time"))
    cpu_time_percent_nice = models.FloatField(_("%CPU Nice Time"))
    cpu_time_percent_system = models.FloatField(_("%CPU System Time"))
    cpu_time_percent_idle = models.FloatField(_("%CPU Idle Time"))
    cpu_count_logical = models.IntegerField(_("CPU Count Logical"), null=True)
    cpu_count_physical = models.IntegerField(_("CPU Count Physical"),
                                             null=True)
    ctx_switches = models.IntegerField(_("Context Switches"))
    interrupts = models.IntegerField(_("Interrupts"))
    soft_interrupts = models.IntegerField(_("Soft Interrupts"))
    sys_calls = models.IntegerField(_("System Calls"))
    cpu_frequency_current = models.FloatField(_("CPU Current Frequency"),
                                              blank=True, null=True)
    cpu_frequency_min = models.FloatField(_("CPU Min Frequency"),
                                          blank=True, null=True)
    cpu_frequency_max = models.FloatField(_("CPU Max Frequency"),
                                          blank=True, null=True)
    load_avg_1_min = models.FloatField(_("Average System Load 1 Minute"))
    load_avg_5_min = models.FloatField(_("Average System Load 5 Minutes"))
    load_avg_15_min = models.FloatField(_("Average System Load 15 Minutes"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.CharField(
        max_length=6,
        choices=LogCategory.choices,
        default=LogCategory.INFORMATION,
    )


class MemoryData(models.Model):
    total_physical_memory = models.FloatField(_("Total Physical Memory"))
    available_physical_memory = models.FloatField(
        _("Available Physical Memory"))
    used_physical_memory = models.FloatField(_("Used Physical Memory"))
    use_percentage_physical_memory = models.FloatField(
        _("Use Percentage Physical Memory"))
    total_swap_memory = models.FloatField(_("Total Swap Memory"))
    free_swap_memory = models.FloatField(_("Free Swap Memory"))
    used_swap_memory = models.FloatField(_("Used Swap Memory"))
    use_percentage_swap_memory = models.FloatField(
        _("Use Percentage Swap Memory"))
    sin_swap_memory = models.FloatField(
        _("Number of Bytes The System Has Swapped In From Disk"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.CharField(
        max_length=6,
        choices=LogCategory.choices,
        default=LogCategory.INFORMATION,
    )


class SensorsData(models.Model):
    battery_percent = models.IntegerField(_("Battery Percentage"))
    is_power_plugged = models.BooleanField(_("Is Power Plugged"))
    sec_left = models.IntegerField(
        _("Approximation of how many seconds"
          " are left before the battery runs out of power")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.CharField(
        max_length=6,
        choices=LogCategory.choices,
        default=LogCategory.INFORMATION,
    )


class DisksData(models.Model):
    device = models.CharField(_('Device'), max_length=255)
    total = models.BigIntegerField(_('Total disk size'))
    used = models.BigIntegerField(_("Used disk size"))
    free = models.BigIntegerField(_("Free disk size"))
    percent = models.FloatField(_("Percent of used disk"))
    type = models.CharField(_("Type of disk"), max_length=255)
    mountpoint = models.CharField(_("Mountpoint"), max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.CharField(
        max_length=6,
        choices=LogCategory.choices,
        default=LogCategory.INFORMATION,
    )

log_aggregation_sys/data_saver/models.py
# Create your models here.

log_aggregation_sys/data_logger/forms.py
from django import forms


class EmailForm(forms.Form):
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs={'required': "required"}),
    )

log_aggregation_sys/data_logger/views.py
from data_collector.models import CpuData, DisksData, MemoryData, SensorsData
from data_logger.filters import (CpuDataFilter, DiskDataFilter,
                                 MemoryDataFilter, SensorsDataFilter)
from data_logger.forms import EmailForm
from django.http import Http404
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic.list import ListView, MultipleObjectMixin

from django.conf import settings


def main_menu_view(request):
    return render(request, "main_menu/main_menu.html")


class BaseDataView(ListView, MultipleObjectMixin):
    formset_class = EmailForm

    def get_ordering(self):
        ordering = self.request.GET.get("ordering", "-created_at")
        return ordering

    def get_queryset(self):
        qs = super().get_queryset()
        self.filter = self.filterset_class(self.request.GET, queryset=qs)
        return self.filter.qs, self.filter

    def get(self, request, *args, **kwargs):
        self.object_list, filter = self.get_queryset()
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(
                self.object_list, "exists"
            ):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        context = self.get_context_data()
        context["data_filter"] = filter
        context["email_form"] = EmailForm

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):

        form = EmailForm(request.POST)
        if form.is_valid():
            settings.ALERT_EMAIL_ADDRESS = form.cleaned_data.get("email")
        return redirect(request.get_full_path())


class CpuDataView(BaseDataView):
    model = CpuData
    queryset = CpuData.objects.all()
    filterset_class = CpuDataFilter
    template_name = "data_logger/cpu_data.html"


class MemoryDataView(BaseDataView):
    model = MemoryData
    queryset = MemoryData.objects.all()
    filterset_class = MemoryDataFilter
    template_name = "data_logger/memory_data.html"


class SensorsDataView(BaseDataView):
    model = SensorsData
    queryset = SensorsData.objects.all()
    filterset_class = SensorsDataFilter
    template_name = "data_logger/sensors_data.html"


class DiskDataView(BaseDataView):
    model = DisksData
    queryset = DisksData.objects.all()
    filterset_class = DiskDataFilter
    template_name = "data_logger/disk_data.html"

log_aggregation_sys/data_saver/views.py
# Create your views here.

log_aggregation_sys/templates/data_logger/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="{% static '/css/base.css' %}" type="text/css" />
    {% block head %}
    {% endblock head %}
  </head>
  <body>
    <div class="navbar">
      <div class="container">
        <a class="logo" href="">Data<span>Logger</span></a>
        <nav>
          <ul>
            <li class="index-hl"><a href="{% url 'data_logger:main_menu' %}">Main Menu</a></li>

            {% if request.path != '/cpu_data/' %}
            <li class="index-hl"><a href="{% url 'data_logger:cpu_data' %}">Cpu Data</a></li>
            {% endif %}

            {% if request.path != '/memory_data/' %}
            <li class="index-hl"><a href="{% url 'data_logger:memory_data' %}">Memory Data</a></li>
            {% endif %}

            {% if request.path != '/sensors_data/' %}
            <li class="index-hl"><a href="{% url 'data_logger:sensors_data' %}">Sensors Data</a></li>
            {% endif %}

            {% if request.path != '/disk_data/' %}
            <li class="index-hl"><a href="{% url 'data_logger:disk_data' %}">Disk Data</a></li>
            {% endif %}

          </ul>
        </nav>
        <form method="post">
          <p>
        {% csrf_token %}
        {{ email_form.as_p }}
        <input type="submit" value="Submit" style="display: inline;" >
          </p>
        </form>
        </div>

      </div>


    </div>
    {% block content %}
    {% endblock content %}
  </body>
<script>
  window.setTimeout(function () {
    location.href = window.location.href;
}, 5000); // refresh/redirect after 5 seconds.
</script>
</html>

log_aggregation_sys/templates/data_logger/cpu_data.html
{% extends 'data_logger/base.html' %}
{% load static %}
{% load data_filtering %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cpu_data.css' %}" type="text/css" />
<title>CPU</title>
{% endblock head %}

{% block content %}

<form method="get" >
    <div class="filtering">
    {{ data_filter.form.as_p }}
        <input type="submit" />
        <p>Number of registered logs: {{object_list.count}}</p>

    </div>

</form>
<div style="overflow-x:auto;">
<table>
    <tr>
        <th>Created at
            <a href="{{request.path}}?{% url_replace '-created_at' %}">
                <img src="{% static 'imgs/sort-button-asc.png' %}" alt="sort button ascending" width="20" height="20">
            </a>
            <a href="{{request.path}}?{% url_replace 'created_at' %}">
                <img src="{% static 'imgs/sort-button-desc.png' %}" alt="sort button descending" width="20" height="20">
            </a>
        </th>
        <th> User Time </th>
        <th> Nice Time </th>
        <th> System Time </th>
        <th> Idle Time </th>
        <th> %Cpu </th>
        <th> %CPU User Time </th>
        <th> %CPU Nice Time </th>
        <th> %CPU System Time </th>
        <th> %CPU Idle Time </th>
        <th> CPU Count Logical </th>
        <th> CPU Count Physical </th>
        <th> Context Switches </th>
        <th> Interrupts </th>
        <th> Soft Interrupts </th>
        <th> System Calls</th>
        <th> CPU Current Frequency </th>
        <th> CPU Min Frequency </th>
        <th> CPU Max Frequency </th>
        <th> Average System Load 1 Minute </th>
        <th> Average System Load 5 Minutes </th>
        <th> Average System Load 15 Minutes </th>

    </tr>
    {% for cpu in object_list %}
    {% if cpu.category == "INFO"%}
    <tr style="background: lightblue;">
        <td>{{cpu.created_at}}</td>
        <td>{{cpu.user_time}}</td>
        <td>{{cpu.nice_time}}</td>
        <td>{{cpu.system_time}}</td>
        <td>{{cpu.idle_time}}</td>
        <td>{{cpu.cpu_percent}}%</td>
        <td>{{cpu.cpu_time_percent_user}}%</td>
        <td>{{cpu.cpu_time_percent_nice}}%</td>
        <td>{{cpu.cpu_time_percent_system}}%</td>
        <td>{{cpu.cpu_time_percent_idle}}%</td>
        <td>{{cpu.cpu_count_logical}}</td>
        <td>{{cpu.cpu_count_physical}}</td>
        <td>{{cpu.ctx_switches}}</td>
        <td>{{cpu.interrupts}}</td>
        <td>{{cpu.soft_interrupts}}</td>
        <td>{{cpu.sys_calls}}</td>
        <td>{{cpu.cpu_frequency_current}}</td>
        <td>{{cpu.cpu_frequency_min}}</td>
        <td>{{cpu.cpu_frequency_max}}</td>
        <td>{{cpu.load_avg_1_min}}</td>
        <td>{{cpu.load_avg_5_min}}</td>
        <td>{{cpu.load_avg_15_min}}</td>
    </tr>
    {% elif cpu.category == "WRN"%}
    <tr style="background: #e8db13;">
        <td>{{cpu.created_at}}</td>
        <td>{{cpu.user_time}}</td>
        <td>{{cpu.nice_time}}</td>
        <td>{{cpu.system_time}}</td>
        <td>{{cpu.idle_time}}</td>
        <td>{{cpu.cpu_percent}}%</td>
        <td>{{cpu.cpu_time_percent_user}}%</td>
        <td>{{cpu.cpu_time_percent_nice}}%</td>
        <td>{{cpu.cpu_time_percent_system}}%</td>
        <td>{{cpu.cpu_time_percent_idle}}%</td>
        <td>{{cpu.cpu_count_logical}}</td>
        <td>{{cpu.cpu_count_physical}}</td>
        <td>{{cpu.ctx_switches}}</td>
        <td>{{cpu.interrupts}}</td>
        <td>{{cpu.soft_interrupts}}</td>
        <td>{{cpu.sys_calls}}</td>
        <td>{{cpu.cpu_frequency_current}}</td>
        <td>{{cpu.cpu_frequency_min}}</td>
        <td>{{cpu.cpu_frequency_max}}</td>
        <td>{{cpu.load_avg_1_min}}</td>
        <td>{{cpu.load_avg_5_min}}</td>
        <td>{{cpu.load_avg_15_min}}</td>
    </tr>

    {% elif cpu.category == "ERR"%}
    <tr style="background: #f04d56;">
        <td>{{cpu.created_at}}</td>
        <td>{{cpu.user_time}}</td>
        <td>{{cpu.nice_time}}</td>
        <td>{{cpu.system_time}}</td>
        <td>{{cpu.idle_time}}</td>
        <td>{{cpu.cpu_percent}}%</td>
        <td>{{cpu.cpu_time_percent_user}}%</td>
        <td>{{cpu.cpu_time_percent_nice}}%</td>
        <td>{{cpu.cpu_time_percent_system}}%</td>
        <td>{{cpu.cpu_time_percent_idle}}%</td>
        <td>{{cpu.cpu_count_logical}}</td>
        <td>{{cpu.cpu_count_physical}}</td>
        <td>{{cpu.ctx_switches}}</td>
        <td>{{cpu.interrupts}}</td>
        <td>{{cpu.soft_interrupts}}</td>
        <td>{{cpu.sys_calls}}</td>
        <td>{{cpu.cpu_frequency_current}}</td>
        <td>{{cpu.cpu_frequency_min}}</td>
        <td>{{cpu.cpu_frequency_max}}</td>
        <td>{{cpu.load_avg_1_min}}</td>
        <td>{{cpu.load_avg_5_min}}</td>
        <td>{{cpu.load_avg_15_min}}</td>
    </tr>

    {% endif %}
    {% endfor %}
</table>
    </div>
{% endblock content %}

log_aggregation_sys/templates/data_logger/disk_data.html
{% extends 'data_logger/base.html' %}
{% load static %}
{% load data_filtering %}
{% load template_helpers %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cpu_data.css' %}" type="text/css" />
<title>CPU</title>
{% endblock head %}

{% block content %}

<form method="get" >
    <div class="filtering">
    {{ data_filter.form.as_p }}
        <input type="submit" />
         <p>Number of registered logs: {{object_list.count}}</p>
    </div>

</form>
<div style="overflow-x:auto;">
<table>
    <tr>
        <th>Created at
            <a href="{{request.path}}?{% url_replace '-created_at' %}">
                <img src="{% static 'imgs/sort-button-asc.png' %}" alt="sort button ascending" width="20" height="20">
            </a>
            <a href="{{request.path}}?{% url_replace 'created_at' %}">
                <img src="{% static 'imgs/sort-button-desc.png' %}" alt="sort button descending" width="20" height="20">
            </a>
        </th>
        <th> Device </th>
        <th> Total </th>
        <th> Used </th>
        <th> Free </th>
        <th> Use % </th>
        <th> Type </th>
        <th> Mount </th>

    </tr>
    {% for disk in object_list %}
    {% if disk.category == "INFO"%}
    <tr style="background: lightblue;">
        <td>{{disk.created_at}}</td>
        <td>{{disk.device}}</td>
        <td>{{ disk.total | bytes_attribute_solver}}</td>
        <td>{{ disk.used | bytes_attribute_solver}}</td>
        <td>{{ disk.free | bytes_attribute_solver}}</td>
        <td>{{ disk.percent }}%</td>
        <td>{{ disk.type }}</td>
        <td>{{ disk.mountpoint}}</td>

    </tr>
    {% elif disk.category == "WRN"%}
    <tr style="background: #e8db13;">
        <td>{{disk.created_at}}</td>
        <td>{{disk.device}}</td>
        <td>{{ disk.total | bytes_attribute_solver}}</td>
        <td>{{ disk.used | bytes_attribute_solver}}</td>
        <td>{{ disk.free | bytes_attribute_solver}}</td>
        <td>{{ disk.percent }}%</td>
        <td>{{ disk.type }}</td>
        <td>{{ disk.mountpoint}}</td>
    </tr>

    {% elif disk.category == "ERR"%}
    <tr style="background: #f04d56;">
        <td>{{disk.created_at}}</td>
        <td>{{disk.device}}</td>
        <td>{{ disk.total | bytes_attribute_solver}}</td>
        <td>{{ disk.used | bytes_attribute_solver}}</td>
        <td>{{ disk.free | bytes_attribute_solver}}</td>
        <td>{{ disk.percent }}%</td>
        <td>{{ disk.type }}</td>
        <td>{{ disk.mountpoint }}</td>
    </tr>

    {% endif %}
    {% endfor %}
</table>
    </div>
{% endblock content %}

log_aggregation_sys/templates/data_logger/memory_data.html
{% extends 'data_logger/base.html' %}
{% load static %}
{% load data_filtering %}
{% load template_helpers %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cpu_data.css' %}" type="text/css" />
<title>CPU</title>
{% endblock head %}

{% block content %}

<form method="get" >
    <div class="filtering">
    {{ data_filter.form.as_p }}
        <input type="submit" />
         <p>Number of registered logs: {{object_list.count}}</p>
    </div>

</form>
<div style="overflow-x:auto;">
<table>
    <tr>
        <th>Created at
            <a href="{{request.path}}?{% url_replace '-created_at' %}">
                <img src="{% static 'imgs/sort-button-asc.png' %}" alt="sort button ascending" width="20" height="20">
            </a>
            <a href="{{request.path}}?{% url_replace 'created_at' %}">
                <img src="{% static 'imgs/sort-button-desc.png' %}" alt="sort button descending" width="20" height="20">
            </a>
        </th>
        <th> Total Physical Memory </th>
        <th> Available Physical Memory </th>
        <th> Used Physical Memory </th>
        <th> Use Percentage Physical Memory </th>
        <th> Total Swap Memory </th>
        <th> Free Swap Memory </th>
        <th> Used Swap Memory </th>
        <th> Use Percentage Swap Memory </th>
        <th> Number of Bytes The System Has Swapped In From Disk </th>

    </tr>
    {% for memory in object_list %}
    {% if memory.category == "INFO"%}
    <tr style="background: lightblue;">
        <td>{{memory.created_at}}</td>
        <td>{{memory.total_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.available_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.used_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.use_percentage_physical_memory}}%</td>
        <td>{{memory.total_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.free_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.used_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.use_percentage_swap_memory}}%</td>
        <td>{{memory.sin_swap_memory}}</td>

    </tr>
    {% elif memory.category == "WRN"%}
    <tr style="background: #e8db13;">
        <td>{{memory.created_at}}</td>
        <td>{{memory.total_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.available_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.used_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.use_percentage_physical_memory}}%</td>
        <td>{{memory.total_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.free_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.used_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.use_percentage_swap_memory}}%</td>
        <td>{{memory.sin_swap_memory}}</td>    </tr>

    {% elif memory.category == "ERR"%}
    <tr style="background: #f04d56;">
        <td>{{memory.created_at}}</td>
        <td>{{memory.total_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.available_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.used_physical_memory | bytes_attribute_solver}}</td>
        <td>{{memory.use_percentage_physical_memory}}%</td>
        <td>{{memory.total_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.free_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.used_swap_memory | bytes_attribute_solver}}</td>
        <td>{{memory.use_percentage_swap_memory}}%</td>
        <td>{{memory.sin_swap_memory}}</td>
    </tr>

    {% endif %}
    {% endfor %}
</table>
    </div>
{% endblock content %}

log_aggregation_sys/templates/data_logger/sensors_data.html
{% extends 'data_logger/base.html' %}
{% load static %}
{% load data_filtering %}
{% load template_helpers %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cpu_data.css' %}" type="text/css" />
<title>CPU</title>
{% endblock head %}

{% block content %}

<form method="get" >
    <div class="filtering">
    {{ data_filter.form.as_p }}
        <input type="submit" />
         <p>Number of registered logs: {{object_list.count}}</p>
    </div>

</form>
<div style="overflow-x:auto;">
<table>
    <tr>
        <th>Created at
            <a href="{{request.path}}?{% url_replace '-created_at' %}">
                <img src="{% static 'imgs/sort-button-asc.png' %}" alt="sort button ascending" width="20" height="20">
            </a>
            <a href="{{request.path}}?{% url_replace 'created_at' %}">
                <img src="{% static 'imgs/sort-button-desc.png' %}" alt="sort button descending" width="20" height="20">
            </a>
        </th>
        <th> Battery Percentage </th>
        <th> Is Power Plugged </th>
        <th> Seconds left before the battery runs out of power </th>

    </tr>
    {% for sensor in object_list %}
    {% if sensor.category == "INFO"%}
    <tr style="background: lightblue;">
        <td>{{sensor.created_at}}</td>
        <td>{{sensor.battery_percent}}%</td>
        <td>{{sensor.is_power_plugged|battery_power_plugged_attribute_solver:sensor.battery_percent  }}</td>
        <td>{{sensor.sec_left | battery_sec_left_attribute_solver }}</td>
    </tr>
    {% elif sensor.category == "WRN"%}
    <tr style="background: #e8db13;">
         <td>{{sensor.created_at}}</td>
        <td>{{sensor.battery_percent}}%</td>
        <td>{{sensor.is_power_plugged|battery_power_plugged_attribute_solver:sensor.battery_percent  }}</td>
        <td>{{sensor.sec_left | battery_sec_left_attribute_solver }}</td>
    </tr>

    {% elif sensor.category == "ERR"%}
    <tr style="background: #f04d56;">
        <td>{{sensor.created_at}}</td>
        <td>{{sensor.battery_percent}}%</td>
        <td>{{sensor.is_power_plugged|battery_power_plugged_attribute_solver:sensor.battery_percent  }}</td>
        <td>{{sensor.sec_left | battery_sec_left_attribute_solver }}</td>
    </tr>

    {% endif %}
    {% endfor %}
</table>
    </div>
{% endblock content %}

log_aggregation_sys/templates/main_menu/main_menu.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <link rel="stylesheet" type="text/css" href="{% static '/css/main_menu.css'%}">
</head>
<body>

<div class="container">
  <div class="box box1">
    <a href="{% url 'data_logger:cpu_data' %}" class="fill-div fill-div-box1">Cpu Data</a>
  </div>
  <div class="box box2">
    <a href="{% url 'data_logger:memory_data' %}" class="fill-div fill-div-box2">Memory Data</a>
  </div>
  <div class="box box3">
    <a href="{% url 'data_logger:sensors_data' %}" class="fill-div fill-div-box3">Sensors Data</a>
  </div>
  <div class="box box4">
    <a href="{% url 'data_logger:disk_data' %}" class="fill-div fill-div-box4">Disk Data</a>
  </div>

</div>

</body>
</html>